openapi: 3.1.0
info:
  title: Drone with FlightPlan
  version: 1.0.0
paths: {}
components:
  schemas:
    Drone:
      properties:
        name:
          type: string
          title: Name
          default: ''
          x_frontend_fieldName: Name
          x_frontend_fieldDescription: This is the Drone Name
          x_frontend_editable: true
          x_frontend_placeholder: Write the Name of your Drone
        description:
          type: string
          title: Description
          default: ''
          x_frontend_fieldName: Description
          x_frontend_fieldDescription: This is the Drone Description
          x_frontend_editable: true
          x_frontend_placeholder: Write short description of your Drone
        flightplans:
          type: array
          title: FlightPlans
          items:
            type: string
          default: []
          x_frontend_fieldName: FlightPlans
          x_frontend_fieldDescription: These are the Drone's FlightPlans
          x_frontend_editable: true
          x_frontend_placeholder: List the Drone's FlightPlans
          x_frontend_relation: FlightPlan
        manufacturer:
          type: string
          title: Manufacturer
          default: ''
          x_frontend_fieldName: Manufacturer
          x_frontend_fieldDescription: This is the drone Manufacturer
          x_frontend_editable: true
          x_frontend_placeholder: Select the Manufacturer
          x_frontend_relation: Manufacturer
        ownerId:
          type: string
          title: Owner
          x_frontend_fieldName: Owner
          x_frontend_fieldDescription: This is the Drone Owner
          x_frontend_editable: true
          x_frontend_placeholder: Select the Drone Owner
          x_frontend_relation: DronePilot
      required:
        - name
        - flightplans
      x-frontend-defaultFields:
        - name
        - description
        - manufacturer
        - ownerId
        - flightplans
    FlightPlan:
      properties:
        name:
          type: string
          title: Name
          default: ''
          x_frontend_fieldName: Name
          x_frontend_fieldDescription: This is the Name of the FlightPlan
          x_frontend_editable: true
          x_frontend_placeholder: Write the Name of this FlightPlan
        route:
          $ref: '#/components/schemas/LineString'
          title: Route
          x_frontend_fieldName: Route
          x_frontend_fieldDescription: This is Route of the FlightPlan
          x_frontend_editable: true
          x_frontend_placeholder: Add the coordinates for the Route
          x_frontend_uspaceMap: true
        mission_details:
          type: string
          title: MissionDetails
          default: ''
          x_frontend_fieldName: Mission Details
          x_frontend_fieldDescription: These are the important details for the mission
          x_frontend_editable: true
          x_frontend_placeholder: Write the mission details here
        date:
          type: string
          format: date-time
          title: Date
          x_frontend_fieldName: Flight Date
          x_frontend_fieldDescription: Departure Datetime of the FlightPlan
          x_frontend_editable: true
          x_frontend_placeholder: Select a Datetime
      required:
        - name
      x-frontend-defaultFields:
        - name
        - date
        - mission_details
        - route
    Manufacturer:
      properties:
        name:
          type: string
          title: Name
          default: ''
          x_frontend_fieldName: Name
          x_frontend_fieldDescription: This is the Manufacturer Name
          x_frontend_editable: true
          x_frontend_placeholder: Write the Name of the Manufacturer
        information:
          type: string
          title: Information
          default: ''
          x_frontend_fieldName: Information
          x_frontend_fieldDescription: Information about the Manufacturer
          x_frontend_editable: true
          x_frontend_placeholder: Provide Information about the Manufacturer
        country:
          type: string
          title: Country
          default: ''
          x_frontend_fieldName: Country
          x_frontend_fieldDescription: Country where the Manufacturer is based
          x_frontend_editable: true
          x_frontend_placeholder: Enter the Country of the Manufacturer
        location:
          $ref: '#/components/schemas/Point'
          title: Location
          x_frontend_fieldName: Location
          x_frontend_fieldDescription: Location/Address of the Manufacturer
          x_frontend_editable: true
          x_frontend_placeholder: Enter the Location of the Manufacturer
        contact_information:
          type: string
          title: Contact Information
          default: ''
          x_frontend_fieldName: Contact Information
          x_frontend_fieldDescription: Contact details for the Manufacturer (e.g., Email, Phone)
          x_frontend_editable: true
          x_frontend_placeholder: Provide Contact Information for the Manufacturer
        target_market:
          type: string
          title: Target Market
          default: ''
          x_frontend_fieldName: Target Market
          x_frontend_fieldDescription: Industries served by the Manufacturer
          x_frontend_editable: true
          x_frontend_placeholder: Describe the Target Market of the Manufacturer
        certifications_compliance:
          type: string
          title: Certifications/Compliance
          default: ''
          x_frontend_fieldName: Certifications/Compliance
          x_frontend_fieldDescription: Relevant certifications or regulatory compliance
          x_frontend_editable: true
          x_frontend_placeholder: Describe Certifications/Compliance of the Manufacturer
        social_media_links:
          type: string
          title: Social Media Links
          default: ''
          x_frontend_fieldName: Social Media Links
          x_frontend_fieldDescription: Links to the Manufacturer's social media profiles
          x_frontend_editable: true
          x_frontend_placeholder: Provide Social Media Links for the Manufacturer
        legal_information:
          type: string
          title: Legal Information
          default: ''
          x_frontend_fieldName: Legal Information
          x_frontend_fieldDescription: Patents, trademarks, lawsuits, etc.
          x_frontend_editable: true
          x_frontend_placeholder: Provide Legal Information for the Manufacturer
      required:
        - name
        - country
      x-frontend-defaultFields:
        - name
        - information
        - country
        - location
        - contact_information
        - target_market
        - certifications_compliance
        - social_media_links
        - legal_information
    DronePilot:
      properties:
        name:
          type: string
          title: Name
          default: ''
          x_frontend_fieldName: Name
          x_frontend_fieldDescription: This is the name of the Drone Pilot
          x_frontend_editable: true
          x_frontend_placeholder: Write the Name of the Drone Pilot
        contact_number:
          type: string
          title: Contact Number
          default: ''
          x_frontend_fieldName: Contact Number
          x_frontend_fieldDescription: This is the contact number of the Drone Pilot
          x_frontend_editable: true
          x_frontend_placeholder: Write the contact number here
        address:
          $ref: '#/components/schemas/Point'
          title: Address
          x_frontend_fieldName: Address
          x_frontend_fieldDescription: The address of the Drone Pilot
          x_frontend_editable: true
          x_frontend_placeholder: Enter the address of the Drone Pilot
        dronesOwned:
          type: array
          title: Drones Owned
          items:
            type: string
          default: []
          x_frontend_fieldName: Drones Owned
          x_frontend_fieldDescription: These are the Drones of the Pilot
          x_frontend_editable: true
          x_frontend_placeholder: List the Drones of the Pilot
          x_frontend_relation: Drone
      required:
        - name
        - contact_number
      x-auth: true
      x-frontend-defaultFields:
        - name
        - contact_number
        - address
        - dronesOwned