# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-04-07T16:10:13+00:00

from __future__ import annotations

# modified by laia-gen-lib:

from pydantic import ConfigDict
from laiagenlib.Domain.LaiaBaseModel.LaiaBaseModel import LaiaBaseModel
from laiagenlib.Domain.LaiaUser.LaiaUser import LaiaUser
from laiagenlib.Domain.GeoJSON.Geometry import Type, Geometry, LineString, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class Drone(LaiaBaseModel):
    model_config = ConfigDict(json_schema_extra={'x-frontend-defaultFields': ['name', 'description', 'manufacturer', 'ownerId', 'flightplans']})
    description: Optional[str] = Field('', title='Description', x_frontend_editable=True, x_frontend_fieldDescription="This is the Drone Description", x_frontend_fieldName="Description", x_frontend_placeholder="Write short description of your Drone")
    flightplans: List[str] = Field(..., title='FlightPlans', x_frontend_editable=True, x_frontend_fieldDescription="These are the Drone's FlightPlans", x_frontend_fieldName="FlightPlans", x_frontend_placeholder="List the Drone's FlightPlans", x_frontend_relation="FlightPlan")
    id: Optional[str] = Field('', title='Id', )
    manufacturer: Optional[str] = Field('', title='Manufacturer', x_frontend_editable=True, x_frontend_fieldDescription="This is the drone Manufacturer", x_frontend_fieldName="Manufacturer", x_frontend_placeholder="Select the Manufacturer", x_frontend_relation="Manufacturer")
    name: str = Field(..., title='Name', x_frontend_editable=True, x_frontend_fieldDescription="This is the Drone Name", x_frontend_fieldName="Name", x_frontend_placeholder="Write the Name of your Drone")
    ownerId: Optional[str] = Field(None, title='Owner', x_frontend_editable=True, x_frontend_fieldDescription="This is the Drone Owner", x_frontend_fieldName="Owner", x_frontend_placeholder="Select the Drone Owner", x_frontend_relation="DronePilot")


class DronePilot(LaiaUser):
    model_config = ConfigDict(json_schema_extra={'x-auth': True, 'x-frontend-defaultFields': ['name', 'contact_number', 'address', 'dronesOwned']})
    address: Optional[Point] = Field(None, title='Address', x_frontend_editable=True, x_frontend_fieldDescription="The address of the Drone Pilot", x_frontend_fieldName="Address", x_frontend_placeholder="Enter the address of the Drone Pilot")
    contact_number: str = Field(..., title='Contact Number', x_frontend_editable=True, x_frontend_fieldDescription="This is the contact number of the Drone Pilot", x_frontend_fieldName="Contact Number", x_frontend_placeholder="Write the contact number here")
    dronesOwned: Optional[List[str]] = Field([], title='Drones Owned', x_frontend_editable=True, x_frontend_fieldDescription="These are the Drones of the Pilot", x_frontend_fieldName="Drones Owned", x_frontend_placeholder="List the Drones of the Pilot", x_frontend_relation="Drone")
    email: str = Field(..., title='Email', )
    id: Optional[str] = Field('', title='Id', )
    name: str = Field(..., title='Name', x_frontend_editable=True, x_frontend_fieldDescription="This is the name of the Drone Pilot", x_frontend_fieldName="Name", x_frontend_placeholder="Write the Name of the Drone Pilot")
    password: str = Field(..., title='Password', )
    roles: Optional[List[str]] = Field([], title='Roles', x_frontend_relation="Role")


class FlightPlan(LaiaBaseModel):
    model_config = ConfigDict(json_schema_extra={'x-frontend-defaultFields': ['name', 'date', 'mission_details', 'route']})
    date: Optional[datetime] = Field(None, title='Date', x_frontend_editable=True, x_frontend_fieldDescription="Departure Datetime of the FlightPlan", x_frontend_fieldName="Flight Date", x_frontend_placeholder="Select a Datetime")
    id: Optional[str] = Field('', title='Id', )
    mission_details: Optional[str] = Field('', title='MissionDetails', x_frontend_editable=True, x_frontend_fieldDescription="These are the important details for the mission", x_frontend_fieldName="Mission Details", x_frontend_placeholder="Write the mission details here")
    name: str = Field(..., title='Name', x_frontend_editable=True, x_frontend_fieldDescription="This is the Name of the FlightPlan", x_frontend_fieldName="Name", x_frontend_placeholder="Write the Name of this FlightPlan")
    route: Optional[LineString] = Field(None, title='Route', x_frontend_editable=True, x_frontend_fieldDescription="This is Route of the FlightPlan", x_frontend_fieldName="Route", x_frontend_placeholder="Add the coordinates for the Route", x_frontend_uspaceMap=True)


class Manufacturer(LaiaBaseModel):
    model_config = ConfigDict(json_schema_extra={'x-frontend-defaultFields': ['name', 'information', 'country', 'location', 'contact_information', 'target_market', 'certifications_compliance', 'social_media_links', 'legal_information']})
    certifications_compliance: Optional[str] = Field(
        '', title='Certifications/Compliance'
    )
    contact_information: Optional[str] = Field('', title='Contact Information', x_frontend_editable=True, x_frontend_fieldDescription="Contact details for the Manufacturer (e.g., Email, Phone)", x_frontend_fieldName="Contact Information", x_frontend_placeholder="Provide Contact Information for the Manufacturer")
    country: str = Field(..., title='Country', x_frontend_editable=True, x_frontend_fieldDescription="Country where the Manufacturer is based", x_frontend_fieldName="Country", x_frontend_placeholder="Enter the Country of the Manufacturer")
    id: Optional[str] = Field('', title='Id', )
    information: Optional[str] = Field('', title='Information', x_frontend_editable=True, x_frontend_fieldDescription="Information about the Manufacturer", x_frontend_fieldName="Information", x_frontend_placeholder="Provide Information about the Manufacturer")
    legal_information: Optional[str] = Field('', title='Legal Information', x_frontend_editable=True, x_frontend_fieldDescription="Patents, trademarks, lawsuits, etc.", x_frontend_fieldName="Legal Information", x_frontend_placeholder="Provide Legal Information for the Manufacturer")
    location: Optional[Point] = Field(None, title='Location', x_frontend_editable=True, x_frontend_fieldDescription="Location/Address of the Manufacturer", x_frontend_fieldName="Location", x_frontend_placeholder="Enter the Location of the Manufacturer")
    name: str = Field(..., title='Name', x_frontend_editable=True, x_frontend_fieldDescription="This is the Manufacturer Name", x_frontend_fieldName="Name", x_frontend_placeholder="Write the Name of the Manufacturer")
    social_media_links: Optional[str] = Field('', title='Social Media Links', x_frontend_editable=True, x_frontend_fieldDescription="Links to the Manufacturer's social media profiles", x_frontend_fieldName="Social Media Links", x_frontend_placeholder="Provide Social Media Links for the Manufacturer")
    target_market: Optional[str] = Field('', title='Target Market', x_frontend_editable=True, x_frontend_fieldDescription="Industries served by the Manufacturer", x_frontend_fieldName="Target Market", x_frontend_placeholder="Describe the Target Market of the Manufacturer")
